language: java
sudo: false
jdk:
  - oraclejdk8

install:
  - echo ==== Setting up toolchain.xml ====
  - ls /usr/lib/jvm
  - ls
  - echo ==== Setting up Maven 3.5 for Travis ====
  - wget -O maven.tar.gz http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
  - mkdir maven
  - cd maven ; tar --strip-components 1 -xzf ../maven.tar.gz ; cd ..
  - chmod a+x maven/bin/mvn
  - export M2_HOME=$PWD/maven
  - export PATH=$PWD/maven/bin:${PATH}
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"
  - export CI=TRAVIS
  - hash -r

script:
  - travis_wait 45 mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true clean install

# The following upgrades Java during the build in
# order to work around an older Java 8 compiler issue
# which has problems infering types. Travis ships a
# rather old Java 8 version in its images.

addons:
  apt:
    packages:
      - oracle-java8-installer 
